# Generated by Django 5.2.12 on 2026-03-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('date_publication', models.DateField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('chercheurs', models.ManyToManyField(to='researchers.chercheur')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.domaine')),
            ],
        ),
    ]
